server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: MICROSERVICES
            uri: lb://MICROSERVICES
            predicates:
              - Path=/users/**

          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
                - Path=/hotel/**

          - id: RATINGMICROSERVICE
            uri: lb://RATINGMICROSERVICE
            predicates:
                - Path=/rating/**
#  security:
#    user:
#      name: user
#      password: user

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#okta configuration for api gateway
okta:
  oauth2:
    issuer: https://dev-25898924.okta.com/oauth2/default
    audience: api://default
    client-id: 0oamcms5siJASBZax5d7
    client-secret: hqRjmOs4PjAeyM052NYK17oKDL_8OJ2VzU43P51VXVjY66d6DBrqYMytbrPiKe_N
    scopes: openid, profile, email, offline_access