server:
  port: 8084
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: MICROSERVICES
            uri: lb://MICROSERVICES
            predicates:
              - Path=/users/**

          - id: HOTELSERVICE
            uri: lb://HOTELSERVICE
            predicates:
                - Path=/hotel/**

          - id: RATINGMICROSERVICE
            uri: lb://RATINGMICROSERVICE
            predicates:
                - Path=/rating/**
#  security:
#    user:
#      name: user
#      password: user

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#okta configuration for api gateway
okta:
  oauth2:
    issuer: issuer
    audience: audience
    client-id: = client-id
    client-secret: client-secret
    scopes: openid, profile, email, offline_access