server:
  port: 8083
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: Ratingmicroservices
  application:
    name: RATING-SERVICE
  config:
    import: optional:configserver:http://localhost:8085
  security:
    user:
      name: user
      password: user

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#        defaultZone: http://localhost:8761/eureka
